branches:
  only:
    - master

language: node_js

sudo: false

node_js: latest

cache:
  yarn: true
  directories:
    - .cache
    - node_modules

before_install:
  - git config --global user.name "IniZio"
  - git config --global user.email "newman.kcchow@gmail.com"
  - git clone --branch gh-pages "https://${GH_TOKEN}@${GH_REF}" dist

script:
  - npm run build

after_script:
  - cp heroku.php dist/index.php
  - cd dist
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
